name: "main"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      
      - name: Build
        run: make build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag docker image
        run: docker tag cert-manager-webhook-vkcloud:latest ghcr.io/tarantool/cert-manager-webhook-vkcloud:latest

      - name: Publish docker image to Github Container Registry
        run: docker push ghcr.io/tarantool/cert-manager-webhook-vkcloud:latest
